import '@/styles/globals.css';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import LogRocketProvider from './LogRocketProvider';
import Providers from './providers';

const pretendard = localFont({
  src: './fonts/PretendardVariable.woff2',
  variable: '--font-pretendard',
  display: 'swap',
  weight: '45 920',
});

const blackHanSans = localFont({
  src: './fonts/BlackHanSans-Regular.ttf',
  variable: '--font-blackhansans',
  display: 'swap',
  weight: '400',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={` ${pretendard.variable} ${blackHanSans.variable} antialiased`}>
        <LogRocketProvider />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
